const LIST_LOCATION_POP_IDENTITY = { windowId: '1', name: 'LIST_LOCATION_POP' };
const DELAY_CALL_SEARCH = 500;
const SERVICES_STATUS = {
  LOADING: 'LOADING',
  UPDATE: 'UPDATE',
  FAIL: 'FAIL',
};
const TIMEOUT_REQUEST = 15000;

export { LIST_LOCATION_POP_IDENTITY, DELAY_CALL_SEARCH, SERVICES_STATUS, TIMEOUT_REQUEST };
